enum 50501 "Record Deletion Table Type"
{
    Extensible = true;

    value(0; " ") { Caption = ' '; }
    value(1; "Master") { Caption = 'Master Data'; }
    value(2; "Setup") { Caption = 'Setup'; }
    value(3; "Document") { Caption = 'Document'; }
    value(4; "Ledger") { Caption = 'Ledger'; }
    value(5; "Register") { Caption = 'Register'; }
    value(6; "Archive") { Caption = 'Archive'; }
    value(7; "History") { Caption = 'History'; }
}